BAG OF WORDS

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
CV = CountVectorizer()

In [7]:
data = [
    'i am a boy and i am also a man but i am not a girl or a woman',
    'she did not know what she is about to do but i think i know what she is going to do',
    'do you have any idea how much i have worked to be this successful today',
    'only blabbering will take you nowhere i dod not reach where i am today by blabbering'
    'hope this many words that i wrote are enough to give the context i am trying to set'
    ]

In [9]:
count_vec = CV.fit_transform(data)

In [10]:
type(count_vec)

scipy.sparse._csr.csr_matrix

In [11]:
BagOfWords = pd.DataFrame(count_vec.toarray(), columns = CV.get_feature_names_out())

In [12]:
BagOfWords

,about,also,am,and,any,are,be,blabbering,blabberinghope,boy,...,today,trying,what,where,will,woman,words,worked,wrote,you
0,0,1,3,1,0,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
2,0,0,0,0,1,0,1,0,0,0,...,1,0,0,0,0,0,0,1,0,1
3,0,0,2,0,0,1,0,1,1,0,...,1,1,0,1,1,0,1,0,1,1

TF- IDF (Term Frequency Inverse Document Frequency)

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
TFIDF = TfidfVectorizer()
TFIDF_fit = TFIDF.fit_transform(data)

In [13]:
TFIDF_bag = pd.DataFrame(TFIDF_fit.toarray(), columns=TFIDF.get_feature_names_out())

In [14]:
TFIDF_bag

      about      also        am  ...    worked     wrote       you
0  0.000000  0.270931  0.640815  ...  0.000000  0.000000  0.000000
1  0.182135  0.000000  0.000000  ...  0.000000  0.000000  0.000000
2  0.000000  0.000000  0.000000  ...  0.268281  0.000000  0.211516
3  0.000000  0.000000  0.301301  ...  0.000000  0.191081  0.150651

[4 rows x 52 columns]